RDRG-project/RDRG_Back

back/build.gradle, back/src/main/java/com/rdrg/back/common/object/CustomOAuth2User.java, back/src/main/java/com/rdrg/back/config/WebSecurityConfig.java, back/src/main/java/com/rdrg/back/dto/request/SignUpRequestDto.java, back/src/main/java/com/rdrg/back/entity/EmailAuthNumberEntity.java, back/src/main/java/com/rdrg/back/entity/UserEntity.java, back/src/main/java/com/rdrg/back/filter/JwtAuthenticationFilter.java, back/src/main/java/com/rdrg/back/handler/OAuth2SuccessHandler.java, back/src/main/java/com/rdrg/back/provider/JwtProvider.java, back/src/main/java/com/rdrg/back/repository/EmailAuthNumberRepository.java, back/src/main/java/com/rdrg/back/repository/UserRepository.java, back/src/main/java/com/rdrg/back/service/implementation/OAuth2UserServiceImplementation.java
- 보안관련
- WebSecurityConfig 작성 - 5/13
- JwtAuthenticationFilter 작성 중 - 70%작성 - 5/13
- object
- CustomOauth2User 작성 - 5/13
- config
- WebSecurityConfig 작성 - 5/13
- dto
- request - SignUpRequestDto 작성 - 5/13
- entity
- EmailAuthNumberEntity 작성 - 5/13
- UserEntity 작성 - 5/13
- filter
- JwtAuthenticationFilter 작성 - 5/13
- handler
- OAuth2SuccessHandler 작성 - 5/13
- provider
- JwtProvider 작성 - 5/13
- repository
- EmailAuthNumberRepository 작성 - 5/13
- UserRepository 작성 - 5/13
- Service
- implementation - OAuth2UserService 작성 - 5/13
- build.gradle
- 의존성 주입 - 5/13
=> JWT 보안 작업 및 build.gradle 의존성 추가, entity 작업

RDTG_DB.sql, back/src/main/resources/application.properites
=> SQL 쿼리문 작성

RDRG_DB.sql, RDRG_DBver2.sql
=> Jungyoungjong

API 명세서.md
=> API 명세서 작성

back/src/main/java/com/rdrg/back/controller/BoardController.java, back/src/main/java/com/rdrg/back/dto/request/board/PostCommentRequestDto.java, back/src/main/java/com/rdrg/back/dto/request/board/PutBoardRequestDto.java, back/src/main/java/com/rdrg/back/dto/response/board/GetBoardResponseDto.java, back/src/main/java/com/rdrg/back/entity/BoardEntity.java, back/src/main/java/com/rdrg/back/service/BoardService.java, back/src/main/java/com/rdrg/back/service/implementation/BoardServiceImplementation.java
=> board 모듈 작성2

RDRG_DB_ver_2.sql, back/src/main/java/com/rdrg/back/controller/BoardController.java, back/src/main/java/com/rdrg/back/controller/FIleController.java, back/src/main/java/com/rdrg/back/service/BoardService.java, back/src/main/java/com/rdrg/back/service/FileService.java, back/src/main/java/com/rdrg/back/service/implementation/BoardServiceImplementation.java, back/src/main/java/com/rdrg/back/service/implementation/FileServiceImplementation.java
=> 파일 관련 모듈 생성

RDRG_DB_ver_2.sql, back/src/main/java/com/rdrg/back/common/object/DeviceListItem.java, back/src/main/java/com/rdrg/back/dto/request/device/PostDeviceRequestDto.java, back/src/main/java/com/rdrg/back/entity/DeviceEntity.java, back/src/main/java/com/rdrg/back/service/DeviceService.java, back/src/main/java/com/rdrg/back/service/implementation/DeviceServiceImplementation.java, back/src/main/java/com/rdrg/back/service/implementation/UserServiceImplementation.java
=> 테이블 쿼리 수정 및 잡코드 삭제

back/src/main/java/com/rdrg/back/common/object/BoardListItem.java, back/src/main/java/com/rdrg/back/common/util/ChangeDateFormatUtil.java, back/src/main/java/com/rdrg/back/config/WebSecurityConfig.java, back/src/main/java/com/rdrg/back/controller/BoardController.java, back/src/main/java/com/rdrg/back/controller/FIleController.java, back/src/main/java/com/rdrg/back/dto/request/board/PostBoardRequestDto.java, back/src/main/java/com/rdrg/back/dto/response/board/GetBoardResponseDto.java, back/src/main/java/com/rdrg/back/entity/BoardEntity.java, back/src/main/java/com/rdrg/back/entity/UploadEntity.java, back/src/main/java/com/rdrg/back/repository/UploadRepository.java, back/src/main/java/com/rdrg/back/service/implementation/BoardServiceImplementation.java
=> 파일 업로드 api 작성, 오류수정

back/src/main/java/com/rdrg/back/common/util/ChangeDateFormatUtil.java, back/src/main/java/com/rdrg/back/dto/request/auth/SignUpRequestDto.java, back/src/main/java/com/rdrg/back/dto/request/payment/PostPaymentRequestDto.java, back/src/main/java/com/rdrg/back/entity/BoardEntity.java, back/src/main/java/com/rdrg/back/entity/DeviceRentStatusEntity.java, back/src/main/java/com/rdrg/back/repository/PaymentRepository.java, back/src/main/java/com/rdrg/back/service/PaymentService.java, back/src/main/java/com/rdrg/back/service/implementation/PaymentServiceImplementation.java
=> 아이디 패턴 추가 및 대여 정보 저장API 작성중

back/src/main/java/com/rdrg/back/entity/DeviceRentStatusEntity.java
=> 대여 내역 저장 API 작성중

RDRG_DB_ver_2.sql, back/src/main/java/com/rdrg/back/entity/DeviceEntity.java, back/src/main/java/com/rdrg/back/service/implementation/DeviceServiceImplementation.java
=> 디바이스 추가,리스트,삭제 수리

back/src/main/java/com/rdrg/back/controller/PaymentController.java, back/src/main/java/com/rdrg/back/dto/request/payment/PostPaymentRequestDto.java, back/src/main/java/com/rdrg/back/entity/DeviceRentStatusEntity.java, back/src/main/java/com/rdrg/back/service/implementation/PaymentServiceImplementation.java
=> 결제 정보 저장 작성중

back/src/main/java/com/rdrg/back/common/util/ChangeDateFormatUtil.java, back/src/main/java/com/rdrg/back/config/WebSecurityConfig.java, back/src/main/java/com/rdrg/back/dto/request/payment/PostPaymentRequestDto.java
=> 결제 정보 저장API

back/src/main/java/com/rdrg/back/dto/request/payment/PostPaymentRequestDto.java, back/src/main/java/com/rdrg/back/service/implementation/PaymentServiceImplementation.java
=> 페이먼트 조건 추가

back/src/main/java/com/rdrg/back/controller/PaymentController.java, back/src/main/java/com/rdrg/back/dto/response/payment/GetPaymentResponseDto.java, back/src/main/java/com/rdrg/back/repository/PaymentRepository.java, back/src/main/java/com/rdrg/back/service/PaymentService.java, back/src/main/java/com/rdrg/back/service/implementation/PaymentServiceImplementation.java
=> 결제 내역 불러오기 API

back/src/main/java/com/rdrg/back/common/object/RentItem.java, back/src/main/java/com/rdrg/back/controller/PaymentController.java, back/src/main/java/com/rdrg/back/dto/response/payment/GetPaymentListResponseDto.java, back/src/main/java/com/rdrg/back/repository/PaymentRepository.java, back/src/main/java/com/rdrg/back/service/PaymentService.java, back/src/main/java/com/rdrg/back/service/implementation/PaymentServiceImplementation.java
=> 나의 대여 내역불러오기 api

back/src/main/java/com/rdrg/back/config/WebSecurityConfig.java
=> 디바이스 권한 추가

back/src/main/java/com/rdrg/back/repository/DeviceRepository.java, back/src/main/java/com/rdrg/back/service/implementation/DeviceServiceImplementation.java
=> 예약 가능한 리스트 불러오기 (작성중)

back/src/main/java/com/rdrg/back/config/WebSecurityConfig.java, back/src/main/java/com/rdrg/back/controller/DeviceController.java, back/src/main/java/com/rdrg/back/entity/DeviceRentStatusEntity.java, back/src/main/java/com/rdrg/back/repository/DeviceRepository.java, back/src/main/java/com/rdrg/back/service/DeviceService.java, back/src/main/java/com/rdrg/back/service/implementation/DeviceServiceImplementation.java
=> 예약 가능한 기기만 불러오기

back/src/main/java/com/rdrg/back/dto/response/ResponseDto.java, back/src/main/java/com/rdrg/back/dto/response/board/GetBoardResponseDto.java, back/src/main/java/com/rdrg/back/entity/BoardEntity.java, back/src/main/java/com/rdrg/back/service/implementation/DeviceServiceImplementation.java, back/src/main/java/com/rdrg/back/service/implementation/UserServiceImplementation.java
=> 보드 이미지리스트 추가

back/src/main/java/com/rdrg/back/dto/response/board/GetBoardResponseDto.java, back/src/main/java/com/rdrg/back/entity/BoardEntity.java, back/src/main/java/com/rdrg/back/repository/BoardRepository.java, back/src/main/java/com/rdrg/back/repository/UploadRepository.java, back/src/main/java/com/rdrg/back/service/implementation/BoardServiceImplementation.java
=> 게시물 불러오기 수정(url값 같이 불러옴)

RDRG_DB_Ver_3.sql, back/src/main/java/com/rdrg/back/controller/FIleController.java, back/src/main/java/com/rdrg/back/dto/request/board/PutBoardRequestDto.java, back/src/main/java/com/rdrg/back/service/implementation/BoardServiceImplementation.java
=> 게시물 수정 오류 잡기1

back/src/main/java/com/rdrg/back/dto/request/payment/PostPaymentRequestDto.java, back/src/main/java/com/rdrg/back/service/implementation/PaymentServiceImplementation.java
=> rent Status 수정

back/src/main/java/com/rdrg/back/common/object/NameList.java, back/src/main/java/com/rdrg/back/common/object/RentItem.java, back/src/main/java/com/rdrg/back/dto/response/payment/GetPaymentListResponseDto.java
=> 나의 대여내역 불러오기 수정중

back/src/main/java/com/rdrg/back/dto/response/payment/GetPaymentDetailListResponseDto.java, back/src/main/java/com/rdrg/back/repository/PaymentRepository.java, back/src/main/java/com/rdrg/back/service/implementation/PaymentServiceImplementation.java
=> 상세내역 불러오기 api-2

back/src/main/java/com/rdrg/back/service/implementation/BoardServiceImplementation.java
=> 게시물 수정 첨부파일 개별 삭제 추가

API 명세서.md, back/src/main/java/com/rdrg/back/common/object/RentItem.java, back/src/main/java/com/rdrg/back/common/util/KakaoPayUtil.java, back/src/main/java/com/rdrg/back/dto/request/payment/PostPaymentRequestDto.java, back/src/main/java/com/rdrg/back/dto/response/payment/GetPaymentDetailListResponseDto.java, back/src/main/java/com/rdrg/back/entity/DeviceRentStatusEntity.java, back/src/main/java/com/rdrg/back/service/implementation/PaymentServiceImplementation.java
=> rentStatus 상태 변경

back/src/main/java/com/rdrg/back/common/util/KakaoPayUtil.java, back/src/main/java/com/rdrg/back/controller/PaymentController.java, back/src/main/java/com/rdrg/back/dto/response/ResponseCode.java, back/src/main/java/com/rdrg/back/dto/response/ResponseDto.java, back/src/main/java/com/rdrg/back/dto/response/ResponseMessage.java, back/src/main/java/com/rdrg/back/service/PaymentService.java, back/src/main/java/com/rdrg/back/service/implementation/PaymentServiceImplementation.java
=> 예약 내역 삭제 api

back/src/main/java/com/rdrg/back/common/object/RentDetailList.java, back/src/main/java/com/rdrg/back/common/object/RentItem.java, back/src/main/java/com/rdrg/back/common/util/KakaoPayUtil.java, back/src/main/java/com/rdrg/back/dto/response/payment/GetPaymentDetailListResponseDto.java, back/src/main/java/com/rdrg/back/entity/RentDetailEntity.java, back/src/main/java/com/rdrg/back/repository/RentDetailRepository.java, back/src/main/java/com/rdrg/back/service/implementation/PaymentServiceImplementation.java
=> 기기 삭제 api 수정

RDRG_DB_Ver_4.sql
=> database table 수정

back/src/main/java/com/rdrg/back/common/object/DeviceListItem.java, back/src/main/java/com/rdrg/back/controller/DeviceController.java, back/src/main/java/com/rdrg/back/dto/request/auth/SignUpRequestDto.java, back/src/main/java/com/rdrg/back/dto/request/device/PostDeviceRequestDto.java, back/src/main/java/com/rdrg/back/entity/BoardEntity.java, back/src/main/java/com/rdrg/back/entity/DeviceEntity.java, back/src/main/java/com/rdrg/back/repository/DeviceRepository.java, back/src/main/java/com/rdrg/back/service/DeviceService.java, back/src/main/java/com/rdrg/back/service/implementation/DeviceServiceImplementation.java
=> 정규식 수정, 기기 정보 불러오기 지역 추가

back/src/main/java/com/rdrg/back/dto/request/board/PostBoardRequestDto.java, back/src/main/java/com/rdrg/back/service/implementation/BoardServiceImplementation.java, back/src/main/java/com/rdrg/back/service/implementation/FileServiceImplementation.java
=> 오리지널 이름 저장(작성중)

back/src/main/java/com/rdrg/back/common/object/BoardFileItem.java, back/src/main/java/com/rdrg/back/dto/request/board/PostBoardRequestDto.java, back/src/main/java/com/rdrg/back/dto/request/board/PutBoardRequestDto.java, back/src/main/java/com/rdrg/back/entity/UploadEntity.java, back/src/main/java/com/rdrg/back/service/implementation/BoardServiceImplementation.java
=> 게시물 작성, 수정 첨부파일 오리지널 이름표시 추가

back/src/main/java/com/rdrg/back/common/object/BoardFileItem.java
=> BoardFileItem 수정
